netbox_version: "v3.7-2.8.0"
netbox_name: "netbox"
netbox_basepath: ""
netbox_auth: "default"
netbox_port: "127.0.0.1:8181"
netbox_s3_bucket_uri: ""
netbox_prefix: "/srv/{{ netbox_name }}"
netbox_network: "{{ netbox_name }}"
netbox_public_url: "{{ inventory_hostname }}"
netbox_postgres_prefix: "/srv/{{ netbox_name }}-postgres"
netbox_postgres_dbrestore: ""
netbox_redis_prefix: "/srv/{{ netbox_name }}-redis"
netbox_redis_cache_prefix: "/srv/{{ netbox_name }}-redis-cache"
